<a href="https://colab.research.google.com/github/yaswanthkonde-k17/MDS_LAB/blob/main/week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [5]:
import numpy as np
import time

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start_time_list = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
python_list_time = end_time_list - start_time_list
print(f"Python List addition time: {python_list_time:.6f} seconds")

np_array1 = np.arange(size)
np_array2 = np.arange(size)

start_time_numpy = time.time()
result_np_array = np_array1 + np_array2
end_time_numpy = time.time()
numpy_array_time = end_time_numpy - start_time_numpy
print(f"NumPy Array addition time: {numpy_array_time:.6f} seconds")

Python List addition time: 0.082783 seconds
NumPy Array addition time: 0.002923 seconds


In [8]:
import sys
import numpy as np

size = 1000000

python_list = list(range(size))

memory_list = sys.getsizeof(python_list) + sum(sys.getsizeof(item) for item in python_list[:1000]) * (size // 1000) # Sample sum for larger lists for estimation
print(f"Memory used by Python list (approx): {memory_list / (1024 * 1024):.3f} MB")

numpy_array = np.arange(size)
memory_numpy = numpy_array.nbytes
print(f"Memory used by NumPy array: {memory_numpy / (1024 * 1024):.3f} MB")

Memory used by Python list (approx): 34.332 MB
Memory used by NumPy array: 7.629 MB


In [18]:
import numpy as np
l = [1,2,3,4,5]
type(l)
arr1 = np.array(l)
print(arr1)
type(arr1)
arr1.ndim
arr1.size
arr1.shape
arr1.nbytes

[1 2 3 4 5]


40

In [17]:
import numpy as np

my_new_tuple = (100, 200, 300, 400, 500, 600)
print(f"Original tuple: {my_new_tuple}")

new_array_from_tuple = np.array(my_new_tuple)

print(f"\nNumPy array from tuple: {new_array_from_tuple}")
print(f"Type of array: {type(new_array_from_tuple)}")
print(f"Number of dimensions (ndim): {new_array_from_tuple.ndim}")
print(f"Size of array (total elements): {new_array_from_tuple.size}")
print(f"Shape of array: {new_array_from_tuple.shape}")

Original tuple: (100, 200, 300, 400, 500, 600)

NumPy array from tuple: [100 200 300 400 500 600]
Type of array: <class 'numpy.ndarray'>
Number of dimensions (ndim): 1
Size of array (total elements): 6
Shape of array: (6,)


In [24]:
l = [((2,3),(4,5))]
arr1 = np.array(l)
type(arr1)
arr1.size
arr1.ndim

3

You're right to ask about that! While `np.array([((2,3),(4,5))])` does create a NumPy array, it actually results in a 3D array, not a 2D one. Let's look at why and how to correctly create a 2D array from a list of tuples.

In [20]:
import numpy as np

l_original = [((2,3),(4,5))]
arr_original = np.array(l_original)

print(f"Original input list: {l_original}")
print(f"Array created: {arr_original}")
print(f"Shape of arr_original: {arr_original.shape}")
print(f"Number of dimensions (ndim) of arr_original: {arr_original.ndim}")

l_2d = [(2, 3), (4, 5)]
arr_2d = np.array(l_2d)

print(f"\nCorrect input list for 2D: {l_2d}")
print(f"NumPy 2D array: {arr_2d}")
print(f"Shape of 2D array: {arr_2d.shape}")
print(f"Number of dimensions (ndim) of arr_2d: {arr_2d.ndim}")

Original input list: [((2, 3), (4, 5))]
Array created: [[[2 3]
  [4 5]]]
Shape of arr_original: (1, 2, 2)
Number of dimensions (ndim) of arr_original: 3

Correct input list for 2D: [(2, 3), (4, 5)]
NumPy 2D array: [[2 3]
 [4 5]]
Shape of 2D array: (2, 2)
Number of dimensions (ndim) of arr_2d: 2


In [29]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(type(arr1))
print(arr1.ndim)
print(arr1.size)
arr2 = np.arange(0,100)
print(arr2)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
9
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [31]:
import numpy as np

multiples= np.arange(0, 101, 9)
print(multiples)


[ 0  9 18 27 36 45 54 63 72 81 90 99]


In [35]:
import numpy as np
arr3 = np.array([1,2,3,4],dtype=float)
print(arr3)
arr3.astype('int')

[1. 2. 3. 4.]


array([1, 2, 3, 4])

In [43]:
import numpy as np
arr4 = np.array([[1,2,3],[5,6,7]])
print(arr4)
print(arr4.ndim)



[[1 2 3]
 [5 6 7]]
2


In [51]:
import numpy as np
arr_1d = np.arange(1, 10)
mat = arr_1d.reshape(3, 3)
print(mat)
print(mat.ndim)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [56]:
mat1 = np.zeros((4,4))
print(mat1)
print(mat1.astype("int"))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [58]:
mat2 = np.ones((3,3),int)
print(mat2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [62]:
mat3 = np.eye(3,dtype=int)
print(mat3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [68]:
mat4 = np.random.random((3,3))
print(mat4)
mat5 = np.random.random((5))
print(mat5)
mat6 = np.linspace(10,20,5)
print(mat6)

[[0.89435341 0.2839233  0.76021234]
 [0.38046811 0.85990136 0.80812975]
 [0.74754245 0.76582516 0.35528634]]
[0.57972674 0.70507942 0.17422557 0.73669145 0.8878333 ]
[10.  12.5 15.  17.5 20. ]


In [75]:
mat7 = np.arange(0,20).reshape(4,5)
print(mat7)
mat8 = mat7.ravel()
print(mat8)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
